// Generated by CoffeeScript 1.6.3
(function() {
  var Enigma, arrayToString, caesarCipher, decode, encode, letterToNumber, numberToLetter, stringToArray;

  letterToNumber = function(letter) {
    var temp;
    if (letter.length !== 1) {
      throw "should be single length string";
    }
    temp = letter.toLowerCase().charCodeAt(0);
    if (temp < 97 || temp > 122) {
      throw "must be a letter between a and z";
    }
    return temp - 96;
  };

  numberToLetter = function(number) {
    if (number > 26 || number < 1) {
      throw "not in range";
    }
    return String.fromCharCode(number + 96);
  };

  stringToArray = function(string) {
    var char, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = string.length; _i < _len; _i++) {
      char = string[_i];
      _results.push(letterToNumber(char));
    }
    return _results;
  };

  arrayToString = function(array) {
    return array.map(numberToLetter).join("");
  };

  caesarCipher = function(message, key) {
    var a, b;
    a = stringToArray(message);
    b = a.map(function(i) {
      return i + key;
    });
    return arrayToString(b);
  };

  encode = function(message, key) {
    return caesarCipher(message, key);
  };

  decode = function(message, key) {
    return caesarCipher(message, -key);
  };

  Enigma = (function() {
    function Enigma(state) {
      this.state = state;
    }

    Enigma.prototype.encodeLetter = function(letter) {
      return alert(this.name + (" moved " + meters + "m."));
    };

    return Enigma;

  })();

}).call(this);
